fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: en
            editor: ckeditor
            fullscreen: true
            theme: smoothness

            connector:
                debug: false
                roots:
                    uploads:
                        show_hidden: false
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
