twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'form/_bootstrap_5_layout.html.twig'

    globals:
        site_name: '%env(string:SITE_NAME)%'
        site_url: '%env(string:SITE_URL)%'
        site_urlFull: '%env(string:SITE_URL_FULL)%'
        site_mail: '%env(string:SITE_CONTACT)%'
        site_author: '%env(string:SITE_AUTHOR)%'
        site_slogan: '%env(string:SITE_SLOGAN)%'
        site_version: '%env(VERSION)%'

        facebook: '%env(string:SOCIAL_NETWORK_FACEBOOK)%'
        twitter: '%env(string:SOCIAL_NETWORK_TWITTER)%'
        github: '%env(string:SOCIAL_NETWORK_GITHUB)%'
        citizenz: '%env(string:SOCIAL_NETWORK_CITIZENZ)%'

        sidebar_populars_torrents: '%env(SIDEBAR_POPULAR_TORRENT)%'
        sidebar_last_comments: '%env(SIDEBAR_LAST_COMMENTS)%'
