about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'about/index.html.twig'
        maxAge: 86400
        sharedAge: 86400
